### ISSUE TITLE
Remove releaser or fansub group from file title

### ISSUE THREAD

**Issue by Emasoft** [mancuniancol/plugin.video.torrentrssviewer#1]
There is a problem with many RSS feeds. The kodi .strm file name and the directory name are parsed and saved including the releaser or fansub group from the file title.

This causes a mess, because the releaser or group name is written with the movie name and that makes impossible for the Kodi parsers to identify the media content.
 
Because usually the releaser or fansub group name is written in the file name between brackets (i.e. [GROUP] or (GROUP)) while the title of the episode is not, it can and should be removed from the file name when parsing the RSS feed.

Here is a Python method that does exactly this:

```python
def remove_text_inside_brackets(text, brackets="()[]"):
    count = [0] * (len(brackets) // 2) # count open/close brackets
    saved_chars = []
    for character in text:
        for i, b in enumerate(brackets):
            if character == b: # found bracket
                kind, is_close = divmod(i, 2)
                count[kind] += (-1)**is_close # `+1`: open, `-1`: close
                if count[kind] < 0: # unbalanced bracket
                    count[kind] = 0
                break
        else: # character is not a bracket
            if not any(count): # outside brackets
                saved_chars.append(character)
    return ''.join(saved_chars)

print(repr(remove_text_inside_brackets(
    "This is a sentence. (once a day) [twice a day]")))
# -> 'This is a sentence.  '
```

Currently your code removes the brackets, but not the CONTENT of the brackets. This script should be added before your filter.

Can you add this filter to TorrentRSSviewer?

**Comment by mancuniancol** [comment]
That is my point. I have that already implemented. 

value = re.sub('^[.?]', '', value) # erase [HorribleSub] for ex.
I could add the parenthesis, though

**Comment by mancuniancol** [comment]
Any, I am not close to my pc. I will check that this weekend. Could you give me a couple examples to run. I will check better you code to sew if it is better than re.sub function

**Comment by Emasoft** [comment]
@mancuniancol Thank you. Also I strongly suggest you to use the kodi XEM scraper to identify media content, not TVDB. XEM is an index that merge together and synch the metadatas of all other services (TVDB, AniDB, rage, scene, etc.), and it is better than all of them.

XEM
https://github.com/tamland/xbmc-xem
http://thexem.de
