### ISSUE TITLE
Problem with adding RSS feeds

### ISSUE THREAD

**Issue by palradu** [mancuniancol/plugin.video.torrentrssviewer#2]
Hi,

I've installed your add-on but I'm having trouble with adding RSS feeds. If I try to add them, the adding process works alright, but when the list refreshes, there's nothing in the list. I tried it a couple of times and got the same result. The only time the list would populate would ve if I'd restart my Raspberry Pi right after adding the feeds. But if you'd click on them, nothing would open and after a secomd restart the list would be empty again.

I took a look at the addon's directories and I found the file that stores the feeds and tried to add them manually, to see if it works like that. No go.

Think you could help? I'm running Kodi 16.1 on a Raspberry Pi 3. Let me know if you need additional info.

Thank you in advance!

**Comment by mancuniancol** [comment]
Well, there is a problem with the metahandler script that I was using to populate the information.  You need to disable that in the settings. I will give you the information faster.  I am working to do a solution, but it will take me couple weeks.

**Comment by palradu** [comment]
OK, cool. Thank you so much for the reply. Think you could tell me the exact option I should disable in the settings, please?

**Comment by mancuniancol** [comment]
Enable MetaInformation (Poster, Fanart, Plot, ...)
