### ISSUE TITLE
RSS to Quasar

### ISSUE THREAD

**Issue by p0werfool** [mancuniancol/plugin.video.torrentrssviewer#3]
Hello,

I am trying to use the RSS feed 
http://www.bollywoodhungama.com/rss/release_dates.xml

It parses the titles correctly, and when I click on the them, I see Quasar dialog opening but it is not able to process them with any providers. The providers works correctly when I use Trakt or other categories.  

I was expecting that when I click on title, quasar would search for title and choose the stream automatically or present available stream options. Is that possible?

Thanks!

**Comment by mancuniancol** [comment]
You need to use actually rss which contains torrent information. Like https://showrss.info or 
http://extratorrent.cc/rss.xml?type=popular

In other words, if you can use it in utorrent. You can use it here.
